### ISSUE TITLE
Feedsta isn't available on F-Droid

### ISSUE THREAD

**Issue by gasull** [amnesica/Feedsta-Viewer-for-Instagram#1]
Not really a bug but a feature request.  Thank you.

**Comment by amnesica** [comment]
Thanks for the request! I will definitely consider it! But this will take some time.

**Comment by gasull** [comment]
I just realized the repository contains only a README file.  I think it's very misleading having a GitHub repository when the app isn't open-source.

**Comment by amnesica** [comment]
Yes that's right, I will delete the link to Github on the app.
